---
- name: Read distro specific variables.
  ansible.builtin.include_vars: '{{ ansible_os_family | lower }}.yml'

- name: Install nginx.
  ansible.builtin.package:
    name: '{{ nginx_package }}'
    state: present

- name: Install nginx modules.
  ansible.builtin.dnf:
    name: nginx-all-modules
    state: present
  when: (ansible_os_family | lower) == 'redhat'

- name: Main nginx configuration.
  ansible.builtin.template:
    src: '{{ nginx_main_config }}'
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    validate: nginx -t -c %s

- name: Enable selinux boolean
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when:
    - nginx_manage_selinux
    - ansible_selinux is defined
    - ansible_selinux
    - ansible_selinux.status == 'enabled'

# https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#the-validate-option-is-not-enough-for-my-needs-what-do-i-do
- name: Add common configuration files
  ansible.builtin.include_tasks:
    file: unsafe-conf.yml
    apply:
      tags: nginx_static
  tags: nginx_static
  loop: '{{ nginx_static_files }}'

- name: Add custom site definitions.
  ansible.builtin.import_tasks: sites.yml
  tags: nginx_sites

- name: Add custom streams definitions.
  ansible.builtin.import_tasks: streams.yml
  tags: nginx_streams

- name: Ensure nginx is up and running.
  ansible.builtin.service:
    name: nginx.service
    state: started
    enabled: yes
