---
- name: Add custom site definitions.
  ansible.builtin.include_tasks: unsafe-conf.yml
  loop: '{{ nginx_configured_sites }}'

- name: Cleanup manually added sites.
  when: nginx_exclusive_sites
  block:
    - name: Find installed sites.
      ansible.builtin.find:
        paths: /etc/nginx/conf.d
        patterns: '*.conf'
      register: ng_sites

    - name: Clean up installed sites.
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      when: (item | replace("/etc/nginx/", "")) is not in nginx_configured_sites_dest
      loop: '{{ ng_sites["files"] | map(attribute="path") }}'
