---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
    - name: Install python cryptography lib
      ansible.builtin.apt:
        name: python3-openssl
        state: present
      when: ansible_os_family | lower == "debian"
